locking-server:
  image: locking-server
  environment:
    # The start of active environment variables. Set as needed.
    - MONGODB_IP=database2
    # - MONGODB_PORT
    # - MONGODB_DATABASE=USE_HASKELL_DB
    - LOG_LEVEL=DEBUG
    # - https_proxy=http://www-proxy.scss.tcd.ie:8080
    # - http_proxy=http://www-proxy.scss.tcd.ie:8080
  command: /usr/local/bin/locking-server-exe
  ports:
    - "8040:8040"
  links:
    - database2
database2:
  image: mongo:3.0.2
  ports:
    - "27012:27017"
